# Generated by Django 2.2.13 on 2020-09-11 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
