# Generated by Django 3.1.1 on 2021-05-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_generatedimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimages',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
