# Generated by Django 3.1.1 on 2021-05-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210527_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedimages',
            old_name='first_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='generatedimages',
            name='img',
            field=models.ImageField(default='0000', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='generatedimages',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
