# Generated by Django 3.1.1 on 2021-05-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210528_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedimages',
            old_name='name',
            new_name='img_name',
        ),
        migrations.AlterField(
            model_name='generatedimages',
            name='img',
            field=models.ImageField(upload_to='images/', verbose_name='Our Image'),
        ),
    ]
